version: '3.9'

services:
  frontend:
    build: .
    image: project-management-frontend
    restart: always
    ports:
      - "82:82"
    networks:
      pm_network:
        aliases:
          - frontend

networks:
  pm_network:
    external: true
