
services:
  backend:
    build: .
    image: project-management-backend:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    ports:
      - '3002:3002'
    command: ["./docker-entrypoint.sh"]

