
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BudgetLine` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BudgetLine
 * 
 */
export type BudgetLineModel = runtime.Types.Result.DefaultSelection<Prisma.$BudgetLinePayload>

export type AggregateBudgetLine = {
  _count: BudgetLineCountAggregateOutputType | null
  _avg: BudgetLineAvgAggregateOutputType | null
  _sum: BudgetLineSumAggregateOutputType | null
  _min: BudgetLineMinAggregateOutputType | null
  _max: BudgetLineMaxAggregateOutputType | null
}

export type BudgetLineAvgAggregateOutputType = {
  plannedAmount: number | null
}

export type BudgetLineSumAggregateOutputType = {
  plannedAmount: number | null
}

export type BudgetLineMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  category: $Enums.BudgetCategory | null
  budgetType: $Enums.BudgetType | null
  description: string | null
  plannedAmount: number | null
  status: $Enums.ApprovalStatus | null
  approvedBy: string | null
  approvalDate: Date | null
}

export type BudgetLineMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  category: $Enums.BudgetCategory | null
  budgetType: $Enums.BudgetType | null
  description: string | null
  plannedAmount: number | null
  status: $Enums.ApprovalStatus | null
  approvedBy: string | null
  approvalDate: Date | null
}

export type BudgetLineCountAggregateOutputType = {
  id: number
  projectId: number
  category: number
  budgetType: number
  description: number
  plannedAmount: number
  status: number
  approvedBy: number
  approvalDate: number
  _all: number
}


export type BudgetLineAvgAggregateInputType = {
  plannedAmount?: true
}

export type BudgetLineSumAggregateInputType = {
  plannedAmount?: true
}

export type BudgetLineMinAggregateInputType = {
  id?: true
  projectId?: true
  category?: true
  budgetType?: true
  description?: true
  plannedAmount?: true
  status?: true
  approvedBy?: true
  approvalDate?: true
}

export type BudgetLineMaxAggregateInputType = {
  id?: true
  projectId?: true
  category?: true
  budgetType?: true
  description?: true
  plannedAmount?: true
  status?: true
  approvedBy?: true
  approvalDate?: true
}

export type BudgetLineCountAggregateInputType = {
  id?: true
  projectId?: true
  category?: true
  budgetType?: true
  description?: true
  plannedAmount?: true
  status?: true
  approvedBy?: true
  approvalDate?: true
  _all?: true
}

export type BudgetLineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BudgetLine to aggregate.
   */
  where?: Prisma.BudgetLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BudgetLines to fetch.
   */
  orderBy?: Prisma.BudgetLineOrderByWithRelationInput | Prisma.BudgetLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BudgetLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BudgetLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BudgetLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BudgetLines
  **/
  _count?: true | BudgetLineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BudgetLineAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BudgetLineSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BudgetLineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BudgetLineMaxAggregateInputType
}

export type GetBudgetLineAggregateType<T extends BudgetLineAggregateArgs> = {
      [P in keyof T & keyof AggregateBudgetLine]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBudgetLine[P]>
    : Prisma.GetScalarType<T[P], AggregateBudgetLine[P]>
}




export type BudgetLineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BudgetLineWhereInput
  orderBy?: Prisma.BudgetLineOrderByWithAggregationInput | Prisma.BudgetLineOrderByWithAggregationInput[]
  by: Prisma.BudgetLineScalarFieldEnum[] | Prisma.BudgetLineScalarFieldEnum
  having?: Prisma.BudgetLineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BudgetLineCountAggregateInputType | true
  _avg?: BudgetLineAvgAggregateInputType
  _sum?: BudgetLineSumAggregateInputType
  _min?: BudgetLineMinAggregateInputType
  _max?: BudgetLineMaxAggregateInputType
}

export type BudgetLineGroupByOutputType = {
  id: string
  projectId: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvedBy: string | null
  approvalDate: Date | null
  _count: BudgetLineCountAggregateOutputType | null
  _avg: BudgetLineAvgAggregateOutputType | null
  _sum: BudgetLineSumAggregateOutputType | null
  _min: BudgetLineMinAggregateOutputType | null
  _max: BudgetLineMaxAggregateOutputType | null
}

export type GetBudgetLineGroupByPayload<T extends BudgetLineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BudgetLineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BudgetLineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BudgetLineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BudgetLineGroupByOutputType[P]>
      }
    >
  >



export type BudgetLineWhereInput = {
  AND?: Prisma.BudgetLineWhereInput | Prisma.BudgetLineWhereInput[]
  OR?: Prisma.BudgetLineWhereInput[]
  NOT?: Prisma.BudgetLineWhereInput | Prisma.BudgetLineWhereInput[]
  id?: Prisma.StringFilter<"BudgetLine"> | string
  projectId?: Prisma.StringFilter<"BudgetLine"> | string
  category?: Prisma.EnumBudgetCategoryFilter<"BudgetLine"> | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFilter<"BudgetLine"> | $Enums.BudgetType
  description?: Prisma.StringFilter<"BudgetLine"> | string
  plannedAmount?: Prisma.FloatFilter<"BudgetLine"> | number
  status?: Prisma.EnumApprovalStatusFilter<"BudgetLine"> | $Enums.ApprovalStatus
  approvedBy?: Prisma.StringNullableFilter<"BudgetLine"> | string | null
  approvalDate?: Prisma.DateTimeNullableFilter<"BudgetLine"> | Date | string | null
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  approvedByUser?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  expenses?: Prisma.ExpenseListRelationFilter
}

export type BudgetLineOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  budgetType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  plannedAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  approvalDate?: Prisma.SortOrderInput | Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  approvedByUser?: Prisma.UserOrderByWithRelationInput
  expenses?: Prisma.ExpenseOrderByRelationAggregateInput
}

export type BudgetLineWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BudgetLineWhereInput | Prisma.BudgetLineWhereInput[]
  OR?: Prisma.BudgetLineWhereInput[]
  NOT?: Prisma.BudgetLineWhereInput | Prisma.BudgetLineWhereInput[]
  projectId?: Prisma.StringFilter<"BudgetLine"> | string
  category?: Prisma.EnumBudgetCategoryFilter<"BudgetLine"> | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFilter<"BudgetLine"> | $Enums.BudgetType
  description?: Prisma.StringFilter<"BudgetLine"> | string
  plannedAmount?: Prisma.FloatFilter<"BudgetLine"> | number
  status?: Prisma.EnumApprovalStatusFilter<"BudgetLine"> | $Enums.ApprovalStatus
  approvedBy?: Prisma.StringNullableFilter<"BudgetLine"> | string | null
  approvalDate?: Prisma.DateTimeNullableFilter<"BudgetLine"> | Date | string | null
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  approvedByUser?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  expenses?: Prisma.ExpenseListRelationFilter
}, "id">

export type BudgetLineOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  budgetType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  plannedAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  approvalDate?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BudgetLineCountOrderByAggregateInput
  _avg?: Prisma.BudgetLineAvgOrderByAggregateInput
  _max?: Prisma.BudgetLineMaxOrderByAggregateInput
  _min?: Prisma.BudgetLineMinOrderByAggregateInput
  _sum?: Prisma.BudgetLineSumOrderByAggregateInput
}

export type BudgetLineScalarWhereWithAggregatesInput = {
  AND?: Prisma.BudgetLineScalarWhereWithAggregatesInput | Prisma.BudgetLineScalarWhereWithAggregatesInput[]
  OR?: Prisma.BudgetLineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BudgetLineScalarWhereWithAggregatesInput | Prisma.BudgetLineScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BudgetLine"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"BudgetLine"> | string
  category?: Prisma.EnumBudgetCategoryWithAggregatesFilter<"BudgetLine"> | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeWithAggregatesFilter<"BudgetLine"> | $Enums.BudgetType
  description?: Prisma.StringWithAggregatesFilter<"BudgetLine"> | string
  plannedAmount?: Prisma.FloatWithAggregatesFilter<"BudgetLine"> | number
  status?: Prisma.EnumApprovalStatusWithAggregatesFilter<"BudgetLine"> | $Enums.ApprovalStatus
  approvedBy?: Prisma.StringNullableWithAggregatesFilter<"BudgetLine"> | string | null
  approvalDate?: Prisma.DateTimeNullableWithAggregatesFilter<"BudgetLine"> | Date | string | null
}

export type BudgetLineCreateInput = {
  id: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvalDate?: Date | string | null
  project: Prisma.ProjectCreateNestedOneWithoutBudgetLinesInput
  approvedByUser?: Prisma.UserCreateNestedOneWithoutApprovedBudgetLinesInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutBudgetLineInput
}

export type BudgetLineUncheckedCreateInput = {
  id: string
  projectId: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvedBy?: string | null
  approvalDate?: Date | string | null
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutBudgetLineInput
}

export type BudgetLineUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  project?: Prisma.ProjectUpdateOneRequiredWithoutBudgetLinesNestedInput
  approvedByUser?: Prisma.UserUpdateOneWithoutApprovedBudgetLinesNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutBudgetLineNestedInput
}

export type BudgetLineUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutBudgetLineNestedInput
}

export type BudgetLineCreateManyInput = {
  id: string
  projectId: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvedBy?: string | null
  approvalDate?: Date | string | null
}

export type BudgetLineUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BudgetLineUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BudgetLineListRelationFilter = {
  every?: Prisma.BudgetLineWhereInput
  some?: Prisma.BudgetLineWhereInput
  none?: Prisma.BudgetLineWhereInput
}

export type BudgetLineOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BudgetLineCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  budgetType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  plannedAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  approvalDate?: Prisma.SortOrder
}

export type BudgetLineAvgOrderByAggregateInput = {
  plannedAmount?: Prisma.SortOrder
}

export type BudgetLineMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  budgetType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  plannedAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  approvalDate?: Prisma.SortOrder
}

export type BudgetLineMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  budgetType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  plannedAmount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  approvalDate?: Prisma.SortOrder
}

export type BudgetLineSumOrderByAggregateInput = {
  plannedAmount?: Prisma.SortOrder
}

export type BudgetLineNullableScalarRelationFilter = {
  is?: Prisma.BudgetLineWhereInput | null
  isNot?: Prisma.BudgetLineWhereInput | null
}

export type BudgetLineCreateNestedManyWithoutApprovedByUserInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput> | Prisma.BudgetLineCreateWithoutApprovedByUserInput[] | Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput | Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput[]
  createMany?: Prisma.BudgetLineCreateManyApprovedByUserInputEnvelope
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
}

export type BudgetLineUncheckedCreateNestedManyWithoutApprovedByUserInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput> | Prisma.BudgetLineCreateWithoutApprovedByUserInput[] | Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput | Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput[]
  createMany?: Prisma.BudgetLineCreateManyApprovedByUserInputEnvelope
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
}

export type BudgetLineUpdateManyWithoutApprovedByUserNestedInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput> | Prisma.BudgetLineCreateWithoutApprovedByUserInput[] | Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput | Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput[]
  upsert?: Prisma.BudgetLineUpsertWithWhereUniqueWithoutApprovedByUserInput | Prisma.BudgetLineUpsertWithWhereUniqueWithoutApprovedByUserInput[]
  createMany?: Prisma.BudgetLineCreateManyApprovedByUserInputEnvelope
  set?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  disconnect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  delete?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  update?: Prisma.BudgetLineUpdateWithWhereUniqueWithoutApprovedByUserInput | Prisma.BudgetLineUpdateWithWhereUniqueWithoutApprovedByUserInput[]
  updateMany?: Prisma.BudgetLineUpdateManyWithWhereWithoutApprovedByUserInput | Prisma.BudgetLineUpdateManyWithWhereWithoutApprovedByUserInput[]
  deleteMany?: Prisma.BudgetLineScalarWhereInput | Prisma.BudgetLineScalarWhereInput[]
}

export type BudgetLineUncheckedUpdateManyWithoutApprovedByUserNestedInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput> | Prisma.BudgetLineCreateWithoutApprovedByUserInput[] | Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput | Prisma.BudgetLineCreateOrConnectWithoutApprovedByUserInput[]
  upsert?: Prisma.BudgetLineUpsertWithWhereUniqueWithoutApprovedByUserInput | Prisma.BudgetLineUpsertWithWhereUniqueWithoutApprovedByUserInput[]
  createMany?: Prisma.BudgetLineCreateManyApprovedByUserInputEnvelope
  set?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  disconnect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  delete?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  update?: Prisma.BudgetLineUpdateWithWhereUniqueWithoutApprovedByUserInput | Prisma.BudgetLineUpdateWithWhereUniqueWithoutApprovedByUserInput[]
  updateMany?: Prisma.BudgetLineUpdateManyWithWhereWithoutApprovedByUserInput | Prisma.BudgetLineUpdateManyWithWhereWithoutApprovedByUserInput[]
  deleteMany?: Prisma.BudgetLineScalarWhereInput | Prisma.BudgetLineScalarWhereInput[]
}

export type BudgetLineCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutProjectInput, Prisma.BudgetLineUncheckedCreateWithoutProjectInput> | Prisma.BudgetLineCreateWithoutProjectInput[] | Prisma.BudgetLineUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutProjectInput | Prisma.BudgetLineCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.BudgetLineCreateManyProjectInputEnvelope
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
}

export type BudgetLineUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutProjectInput, Prisma.BudgetLineUncheckedCreateWithoutProjectInput> | Prisma.BudgetLineCreateWithoutProjectInput[] | Prisma.BudgetLineUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutProjectInput | Prisma.BudgetLineCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.BudgetLineCreateManyProjectInputEnvelope
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
}

export type BudgetLineUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutProjectInput, Prisma.BudgetLineUncheckedCreateWithoutProjectInput> | Prisma.BudgetLineCreateWithoutProjectInput[] | Prisma.BudgetLineUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutProjectInput | Prisma.BudgetLineCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.BudgetLineUpsertWithWhereUniqueWithoutProjectInput | Prisma.BudgetLineUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.BudgetLineCreateManyProjectInputEnvelope
  set?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  disconnect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  delete?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  update?: Prisma.BudgetLineUpdateWithWhereUniqueWithoutProjectInput | Prisma.BudgetLineUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.BudgetLineUpdateManyWithWhereWithoutProjectInput | Prisma.BudgetLineUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.BudgetLineScalarWhereInput | Prisma.BudgetLineScalarWhereInput[]
}

export type BudgetLineUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutProjectInput, Prisma.BudgetLineUncheckedCreateWithoutProjectInput> | Prisma.BudgetLineCreateWithoutProjectInput[] | Prisma.BudgetLineUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutProjectInput | Prisma.BudgetLineCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.BudgetLineUpsertWithWhereUniqueWithoutProjectInput | Prisma.BudgetLineUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.BudgetLineCreateManyProjectInputEnvelope
  set?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  disconnect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  delete?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  connect?: Prisma.BudgetLineWhereUniqueInput | Prisma.BudgetLineWhereUniqueInput[]
  update?: Prisma.BudgetLineUpdateWithWhereUniqueWithoutProjectInput | Prisma.BudgetLineUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.BudgetLineUpdateManyWithWhereWithoutProjectInput | Prisma.BudgetLineUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.BudgetLineScalarWhereInput | Prisma.BudgetLineScalarWhereInput[]
}

export type EnumBudgetCategoryFieldUpdateOperationsInput = {
  set?: $Enums.BudgetCategory
}

export type EnumBudgetTypeFieldUpdateOperationsInput = {
  set?: $Enums.BudgetType
}

export type EnumApprovalStatusFieldUpdateOperationsInput = {
  set?: $Enums.ApprovalStatus
}

export type BudgetLineCreateNestedOneWithoutExpensesInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutExpensesInput, Prisma.BudgetLineUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutExpensesInput
  connect?: Prisma.BudgetLineWhereUniqueInput
}

export type BudgetLineUpdateOneWithoutExpensesNestedInput = {
  create?: Prisma.XOR<Prisma.BudgetLineCreateWithoutExpensesInput, Prisma.BudgetLineUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.BudgetLineCreateOrConnectWithoutExpensesInput
  upsert?: Prisma.BudgetLineUpsertWithoutExpensesInput
  disconnect?: Prisma.BudgetLineWhereInput | boolean
  delete?: Prisma.BudgetLineWhereInput | boolean
  connect?: Prisma.BudgetLineWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BudgetLineUpdateToOneWithWhereWithoutExpensesInput, Prisma.BudgetLineUpdateWithoutExpensesInput>, Prisma.BudgetLineUncheckedUpdateWithoutExpensesInput>
}

export type BudgetLineCreateWithoutApprovedByUserInput = {
  id: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvalDate?: Date | string | null
  project: Prisma.ProjectCreateNestedOneWithoutBudgetLinesInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutBudgetLineInput
}

export type BudgetLineUncheckedCreateWithoutApprovedByUserInput = {
  id: string
  projectId: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvalDate?: Date | string | null
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutBudgetLineInput
}

export type BudgetLineCreateOrConnectWithoutApprovedByUserInput = {
  where: Prisma.BudgetLineWhereUniqueInput
  create: Prisma.XOR<Prisma.BudgetLineCreateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput>
}

export type BudgetLineCreateManyApprovedByUserInputEnvelope = {
  data: Prisma.BudgetLineCreateManyApprovedByUserInput | Prisma.BudgetLineCreateManyApprovedByUserInput[]
  skipDuplicates?: boolean
}

export type BudgetLineUpsertWithWhereUniqueWithoutApprovedByUserInput = {
  where: Prisma.BudgetLineWhereUniqueInput
  update: Prisma.XOR<Prisma.BudgetLineUpdateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedUpdateWithoutApprovedByUserInput>
  create: Prisma.XOR<Prisma.BudgetLineCreateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedCreateWithoutApprovedByUserInput>
}

export type BudgetLineUpdateWithWhereUniqueWithoutApprovedByUserInput = {
  where: Prisma.BudgetLineWhereUniqueInput
  data: Prisma.XOR<Prisma.BudgetLineUpdateWithoutApprovedByUserInput, Prisma.BudgetLineUncheckedUpdateWithoutApprovedByUserInput>
}

export type BudgetLineUpdateManyWithWhereWithoutApprovedByUserInput = {
  where: Prisma.BudgetLineScalarWhereInput
  data: Prisma.XOR<Prisma.BudgetLineUpdateManyMutationInput, Prisma.BudgetLineUncheckedUpdateManyWithoutApprovedByUserInput>
}

export type BudgetLineScalarWhereInput = {
  AND?: Prisma.BudgetLineScalarWhereInput | Prisma.BudgetLineScalarWhereInput[]
  OR?: Prisma.BudgetLineScalarWhereInput[]
  NOT?: Prisma.BudgetLineScalarWhereInput | Prisma.BudgetLineScalarWhereInput[]
  id?: Prisma.StringFilter<"BudgetLine"> | string
  projectId?: Prisma.StringFilter<"BudgetLine"> | string
  category?: Prisma.EnumBudgetCategoryFilter<"BudgetLine"> | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFilter<"BudgetLine"> | $Enums.BudgetType
  description?: Prisma.StringFilter<"BudgetLine"> | string
  plannedAmount?: Prisma.FloatFilter<"BudgetLine"> | number
  status?: Prisma.EnumApprovalStatusFilter<"BudgetLine"> | $Enums.ApprovalStatus
  approvedBy?: Prisma.StringNullableFilter<"BudgetLine"> | string | null
  approvalDate?: Prisma.DateTimeNullableFilter<"BudgetLine"> | Date | string | null
}

export type BudgetLineCreateWithoutProjectInput = {
  id: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvalDate?: Date | string | null
  approvedByUser?: Prisma.UserCreateNestedOneWithoutApprovedBudgetLinesInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutBudgetLineInput
}

export type BudgetLineUncheckedCreateWithoutProjectInput = {
  id: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvedBy?: string | null
  approvalDate?: Date | string | null
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutBudgetLineInput
}

export type BudgetLineCreateOrConnectWithoutProjectInput = {
  where: Prisma.BudgetLineWhereUniqueInput
  create: Prisma.XOR<Prisma.BudgetLineCreateWithoutProjectInput, Prisma.BudgetLineUncheckedCreateWithoutProjectInput>
}

export type BudgetLineCreateManyProjectInputEnvelope = {
  data: Prisma.BudgetLineCreateManyProjectInput | Prisma.BudgetLineCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type BudgetLineUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.BudgetLineWhereUniqueInput
  update: Prisma.XOR<Prisma.BudgetLineUpdateWithoutProjectInput, Prisma.BudgetLineUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.BudgetLineCreateWithoutProjectInput, Prisma.BudgetLineUncheckedCreateWithoutProjectInput>
}

export type BudgetLineUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.BudgetLineWhereUniqueInput
  data: Prisma.XOR<Prisma.BudgetLineUpdateWithoutProjectInput, Prisma.BudgetLineUncheckedUpdateWithoutProjectInput>
}

export type BudgetLineUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.BudgetLineScalarWhereInput
  data: Prisma.XOR<Prisma.BudgetLineUpdateManyMutationInput, Prisma.BudgetLineUncheckedUpdateManyWithoutProjectInput>
}

export type BudgetLineCreateWithoutExpensesInput = {
  id: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvalDate?: Date | string | null
  project: Prisma.ProjectCreateNestedOneWithoutBudgetLinesInput
  approvedByUser?: Prisma.UserCreateNestedOneWithoutApprovedBudgetLinesInput
}

export type BudgetLineUncheckedCreateWithoutExpensesInput = {
  id: string
  projectId: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvedBy?: string | null
  approvalDate?: Date | string | null
}

export type BudgetLineCreateOrConnectWithoutExpensesInput = {
  where: Prisma.BudgetLineWhereUniqueInput
  create: Prisma.XOR<Prisma.BudgetLineCreateWithoutExpensesInput, Prisma.BudgetLineUncheckedCreateWithoutExpensesInput>
}

export type BudgetLineUpsertWithoutExpensesInput = {
  update: Prisma.XOR<Prisma.BudgetLineUpdateWithoutExpensesInput, Prisma.BudgetLineUncheckedUpdateWithoutExpensesInput>
  create: Prisma.XOR<Prisma.BudgetLineCreateWithoutExpensesInput, Prisma.BudgetLineUncheckedCreateWithoutExpensesInput>
  where?: Prisma.BudgetLineWhereInput
}

export type BudgetLineUpdateToOneWithWhereWithoutExpensesInput = {
  where?: Prisma.BudgetLineWhereInput
  data: Prisma.XOR<Prisma.BudgetLineUpdateWithoutExpensesInput, Prisma.BudgetLineUncheckedUpdateWithoutExpensesInput>
}

export type BudgetLineUpdateWithoutExpensesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  project?: Prisma.ProjectUpdateOneRequiredWithoutBudgetLinesNestedInput
  approvedByUser?: Prisma.UserUpdateOneWithoutApprovedBudgetLinesNestedInput
}

export type BudgetLineUncheckedUpdateWithoutExpensesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BudgetLineCreateManyApprovedByUserInput = {
  id: string
  projectId: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvalDate?: Date | string | null
}

export type BudgetLineUpdateWithoutApprovedByUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  project?: Prisma.ProjectUpdateOneRequiredWithoutBudgetLinesNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutBudgetLineNestedInput
}

export type BudgetLineUncheckedUpdateWithoutApprovedByUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutBudgetLineNestedInput
}

export type BudgetLineUncheckedUpdateManyWithoutApprovedByUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BudgetLineCreateManyProjectInput = {
  id: string
  category: $Enums.BudgetCategory
  budgetType: $Enums.BudgetType
  description: string
  plannedAmount: number
  status: $Enums.ApprovalStatus
  approvedBy?: string | null
  approvalDate?: Date | string | null
}

export type BudgetLineUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approvedByUser?: Prisma.UserUpdateOneWithoutApprovedBudgetLinesNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutBudgetLineNestedInput
}

export type BudgetLineUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutBudgetLineNestedInput
}

export type BudgetLineUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumBudgetCategoryFieldUpdateOperationsInput | $Enums.BudgetCategory
  budgetType?: Prisma.EnumBudgetTypeFieldUpdateOperationsInput | $Enums.BudgetType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  plannedAmount?: Prisma.FloatFieldUpdateOperationsInput | number
  status?: Prisma.EnumApprovalStatusFieldUpdateOperationsInput | $Enums.ApprovalStatus
  approvedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approvalDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type BudgetLineCountOutputType
 */

export type BudgetLineCountOutputType = {
  expenses: number
}

export type BudgetLineCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  expenses?: boolean | BudgetLineCountOutputTypeCountExpensesArgs
}

/**
 * BudgetLineCountOutputType without action
 */
export type BudgetLineCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLineCountOutputType
   */
  select?: Prisma.BudgetLineCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BudgetLineCountOutputType without action
 */
export type BudgetLineCountOutputTypeCountExpensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExpenseWhereInput
}


export type BudgetLineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  category?: boolean
  budgetType?: boolean
  description?: boolean
  plannedAmount?: boolean
  status?: boolean
  approvedBy?: boolean
  approvalDate?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  approvedByUser?: boolean | Prisma.BudgetLine$approvedByUserArgs<ExtArgs>
  expenses?: boolean | Prisma.BudgetLine$expensesArgs<ExtArgs>
  _count?: boolean | Prisma.BudgetLineCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["budgetLine"]>

export type BudgetLineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  category?: boolean
  budgetType?: boolean
  description?: boolean
  plannedAmount?: boolean
  status?: boolean
  approvedBy?: boolean
  approvalDate?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  approvedByUser?: boolean | Prisma.BudgetLine$approvedByUserArgs<ExtArgs>
}, ExtArgs["result"]["budgetLine"]>

export type BudgetLineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  category?: boolean
  budgetType?: boolean
  description?: boolean
  plannedAmount?: boolean
  status?: boolean
  approvedBy?: boolean
  approvalDate?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  approvedByUser?: boolean | Prisma.BudgetLine$approvedByUserArgs<ExtArgs>
}, ExtArgs["result"]["budgetLine"]>

export type BudgetLineSelectScalar = {
  id?: boolean
  projectId?: boolean
  category?: boolean
  budgetType?: boolean
  description?: boolean
  plannedAmount?: boolean
  status?: boolean
  approvedBy?: boolean
  approvalDate?: boolean
}

export type BudgetLineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "category" | "budgetType" | "description" | "plannedAmount" | "status" | "approvedBy" | "approvalDate", ExtArgs["result"]["budgetLine"]>
export type BudgetLineInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  approvedByUser?: boolean | Prisma.BudgetLine$approvedByUserArgs<ExtArgs>
  expenses?: boolean | Prisma.BudgetLine$expensesArgs<ExtArgs>
  _count?: boolean | Prisma.BudgetLineCountOutputTypeDefaultArgs<ExtArgs>
}
export type BudgetLineIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  approvedByUser?: boolean | Prisma.BudgetLine$approvedByUserArgs<ExtArgs>
}
export type BudgetLineIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  approvedByUser?: boolean | Prisma.BudgetLine$approvedByUserArgs<ExtArgs>
}

export type $BudgetLinePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BudgetLine"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    approvedByUser: Prisma.$UserPayload<ExtArgs> | null
    expenses: Prisma.$ExpensePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    category: $Enums.BudgetCategory
    budgetType: $Enums.BudgetType
    description: string
    plannedAmount: number
    status: $Enums.ApprovalStatus
    approvedBy: string | null
    approvalDate: Date | null
  }, ExtArgs["result"]["budgetLine"]>
  composites: {}
}

export type BudgetLineGetPayload<S extends boolean | null | undefined | BudgetLineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload, S>

export type BudgetLineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BudgetLineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BudgetLineCountAggregateInputType | true
  }

export interface BudgetLineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BudgetLine'], meta: { name: 'BudgetLine' } }
  /**
   * Find zero or one BudgetLine that matches the filter.
   * @param {BudgetLineFindUniqueArgs} args - Arguments to find a BudgetLine
   * @example
   * // Get one BudgetLine
   * const budgetLine = await prisma.budgetLine.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BudgetLineFindUniqueArgs>(args: Prisma.SelectSubset<T, BudgetLineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BudgetLine that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BudgetLineFindUniqueOrThrowArgs} args - Arguments to find a BudgetLine
   * @example
   * // Get one BudgetLine
   * const budgetLine = await prisma.budgetLine.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BudgetLineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BudgetLineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BudgetLine that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BudgetLineFindFirstArgs} args - Arguments to find a BudgetLine
   * @example
   * // Get one BudgetLine
   * const budgetLine = await prisma.budgetLine.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BudgetLineFindFirstArgs>(args?: Prisma.SelectSubset<T, BudgetLineFindFirstArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BudgetLine that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BudgetLineFindFirstOrThrowArgs} args - Arguments to find a BudgetLine
   * @example
   * // Get one BudgetLine
   * const budgetLine = await prisma.budgetLine.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BudgetLineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BudgetLineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BudgetLines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BudgetLineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BudgetLines
   * const budgetLines = await prisma.budgetLine.findMany()
   * 
   * // Get first 10 BudgetLines
   * const budgetLines = await prisma.budgetLine.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const budgetLineWithIdOnly = await prisma.budgetLine.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BudgetLineFindManyArgs>(args?: Prisma.SelectSubset<T, BudgetLineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BudgetLine.
   * @param {BudgetLineCreateArgs} args - Arguments to create a BudgetLine.
   * @example
   * // Create one BudgetLine
   * const BudgetLine = await prisma.budgetLine.create({
   *   data: {
   *     // ... data to create a BudgetLine
   *   }
   * })
   * 
   */
  create<T extends BudgetLineCreateArgs>(args: Prisma.SelectSubset<T, BudgetLineCreateArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BudgetLines.
   * @param {BudgetLineCreateManyArgs} args - Arguments to create many BudgetLines.
   * @example
   * // Create many BudgetLines
   * const budgetLine = await prisma.budgetLine.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BudgetLineCreateManyArgs>(args?: Prisma.SelectSubset<T, BudgetLineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BudgetLines and returns the data saved in the database.
   * @param {BudgetLineCreateManyAndReturnArgs} args - Arguments to create many BudgetLines.
   * @example
   * // Create many BudgetLines
   * const budgetLine = await prisma.budgetLine.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BudgetLines and only return the `id`
   * const budgetLineWithIdOnly = await prisma.budgetLine.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BudgetLineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BudgetLineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BudgetLine.
   * @param {BudgetLineDeleteArgs} args - Arguments to delete one BudgetLine.
   * @example
   * // Delete one BudgetLine
   * const BudgetLine = await prisma.budgetLine.delete({
   *   where: {
   *     // ... filter to delete one BudgetLine
   *   }
   * })
   * 
   */
  delete<T extends BudgetLineDeleteArgs>(args: Prisma.SelectSubset<T, BudgetLineDeleteArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BudgetLine.
   * @param {BudgetLineUpdateArgs} args - Arguments to update one BudgetLine.
   * @example
   * // Update one BudgetLine
   * const budgetLine = await prisma.budgetLine.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BudgetLineUpdateArgs>(args: Prisma.SelectSubset<T, BudgetLineUpdateArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BudgetLines.
   * @param {BudgetLineDeleteManyArgs} args - Arguments to filter BudgetLines to delete.
   * @example
   * // Delete a few BudgetLines
   * const { count } = await prisma.budgetLine.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BudgetLineDeleteManyArgs>(args?: Prisma.SelectSubset<T, BudgetLineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BudgetLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BudgetLineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BudgetLines
   * const budgetLine = await prisma.budgetLine.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BudgetLineUpdateManyArgs>(args: Prisma.SelectSubset<T, BudgetLineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BudgetLines and returns the data updated in the database.
   * @param {BudgetLineUpdateManyAndReturnArgs} args - Arguments to update many BudgetLines.
   * @example
   * // Update many BudgetLines
   * const budgetLine = await prisma.budgetLine.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BudgetLines and only return the `id`
   * const budgetLineWithIdOnly = await prisma.budgetLine.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BudgetLineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BudgetLineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BudgetLine.
   * @param {BudgetLineUpsertArgs} args - Arguments to update or create a BudgetLine.
   * @example
   * // Update or create a BudgetLine
   * const budgetLine = await prisma.budgetLine.upsert({
   *   create: {
   *     // ... data to create a BudgetLine
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BudgetLine we want to update
   *   }
   * })
   */
  upsert<T extends BudgetLineUpsertArgs>(args: Prisma.SelectSubset<T, BudgetLineUpsertArgs<ExtArgs>>): Prisma.Prisma__BudgetLineClient<runtime.Types.Result.GetResult<Prisma.$BudgetLinePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BudgetLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BudgetLineCountArgs} args - Arguments to filter BudgetLines to count.
   * @example
   * // Count the number of BudgetLines
   * const count = await prisma.budgetLine.count({
   *   where: {
   *     // ... the filter for the BudgetLines we want to count
   *   }
   * })
  **/
  count<T extends BudgetLineCountArgs>(
    args?: Prisma.Subset<T, BudgetLineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BudgetLineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BudgetLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BudgetLineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BudgetLineAggregateArgs>(args: Prisma.Subset<T, BudgetLineAggregateArgs>): Prisma.PrismaPromise<GetBudgetLineAggregateType<T>>

  /**
   * Group by BudgetLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BudgetLineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BudgetLineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BudgetLineGroupByArgs['orderBy'] }
      : { orderBy?: BudgetLineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BudgetLineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBudgetLineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BudgetLine model
 */
readonly fields: BudgetLineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BudgetLine.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BudgetLineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  approvedByUser<T extends Prisma.BudgetLine$approvedByUserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BudgetLine$approvedByUserArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  expenses<T extends Prisma.BudgetLine$expensesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BudgetLine$expensesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BudgetLine model
 */
export interface BudgetLineFieldRefs {
  readonly id: Prisma.FieldRef<"BudgetLine", 'String'>
  readonly projectId: Prisma.FieldRef<"BudgetLine", 'String'>
  readonly category: Prisma.FieldRef<"BudgetLine", 'BudgetCategory'>
  readonly budgetType: Prisma.FieldRef<"BudgetLine", 'BudgetType'>
  readonly description: Prisma.FieldRef<"BudgetLine", 'String'>
  readonly plannedAmount: Prisma.FieldRef<"BudgetLine", 'Float'>
  readonly status: Prisma.FieldRef<"BudgetLine", 'ApprovalStatus'>
  readonly approvedBy: Prisma.FieldRef<"BudgetLine", 'String'>
  readonly approvalDate: Prisma.FieldRef<"BudgetLine", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BudgetLine findUnique
 */
export type BudgetLineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * Filter, which BudgetLine to fetch.
   */
  where: Prisma.BudgetLineWhereUniqueInput
}

/**
 * BudgetLine findUniqueOrThrow
 */
export type BudgetLineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * Filter, which BudgetLine to fetch.
   */
  where: Prisma.BudgetLineWhereUniqueInput
}

/**
 * BudgetLine findFirst
 */
export type BudgetLineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * Filter, which BudgetLine to fetch.
   */
  where?: Prisma.BudgetLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BudgetLines to fetch.
   */
  orderBy?: Prisma.BudgetLineOrderByWithRelationInput | Prisma.BudgetLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BudgetLines.
   */
  cursor?: Prisma.BudgetLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BudgetLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BudgetLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BudgetLines.
   */
  distinct?: Prisma.BudgetLineScalarFieldEnum | Prisma.BudgetLineScalarFieldEnum[]
}

/**
 * BudgetLine findFirstOrThrow
 */
export type BudgetLineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * Filter, which BudgetLine to fetch.
   */
  where?: Prisma.BudgetLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BudgetLines to fetch.
   */
  orderBy?: Prisma.BudgetLineOrderByWithRelationInput | Prisma.BudgetLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BudgetLines.
   */
  cursor?: Prisma.BudgetLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BudgetLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BudgetLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BudgetLines.
   */
  distinct?: Prisma.BudgetLineScalarFieldEnum | Prisma.BudgetLineScalarFieldEnum[]
}

/**
 * BudgetLine findMany
 */
export type BudgetLineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * Filter, which BudgetLines to fetch.
   */
  where?: Prisma.BudgetLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BudgetLines to fetch.
   */
  orderBy?: Prisma.BudgetLineOrderByWithRelationInput | Prisma.BudgetLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BudgetLines.
   */
  cursor?: Prisma.BudgetLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BudgetLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BudgetLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BudgetLines.
   */
  distinct?: Prisma.BudgetLineScalarFieldEnum | Prisma.BudgetLineScalarFieldEnum[]
}

/**
 * BudgetLine create
 */
export type BudgetLineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * The data needed to create a BudgetLine.
   */
  data: Prisma.XOR<Prisma.BudgetLineCreateInput, Prisma.BudgetLineUncheckedCreateInput>
}

/**
 * BudgetLine createMany
 */
export type BudgetLineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BudgetLines.
   */
  data: Prisma.BudgetLineCreateManyInput | Prisma.BudgetLineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BudgetLine createManyAndReturn
 */
export type BudgetLineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * The data used to create many BudgetLines.
   */
  data: Prisma.BudgetLineCreateManyInput | Prisma.BudgetLineCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BudgetLine update
 */
export type BudgetLineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * The data needed to update a BudgetLine.
   */
  data: Prisma.XOR<Prisma.BudgetLineUpdateInput, Prisma.BudgetLineUncheckedUpdateInput>
  /**
   * Choose, which BudgetLine to update.
   */
  where: Prisma.BudgetLineWhereUniqueInput
}

/**
 * BudgetLine updateMany
 */
export type BudgetLineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BudgetLines.
   */
  data: Prisma.XOR<Prisma.BudgetLineUpdateManyMutationInput, Prisma.BudgetLineUncheckedUpdateManyInput>
  /**
   * Filter which BudgetLines to update
   */
  where?: Prisma.BudgetLineWhereInput
  /**
   * Limit how many BudgetLines to update.
   */
  limit?: number
}

/**
 * BudgetLine updateManyAndReturn
 */
export type BudgetLineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * The data used to update BudgetLines.
   */
  data: Prisma.XOR<Prisma.BudgetLineUpdateManyMutationInput, Prisma.BudgetLineUncheckedUpdateManyInput>
  /**
   * Filter which BudgetLines to update
   */
  where?: Prisma.BudgetLineWhereInput
  /**
   * Limit how many BudgetLines to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BudgetLine upsert
 */
export type BudgetLineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * The filter to search for the BudgetLine to update in case it exists.
   */
  where: Prisma.BudgetLineWhereUniqueInput
  /**
   * In case the BudgetLine found by the `where` argument doesn't exist, create a new BudgetLine with this data.
   */
  create: Prisma.XOR<Prisma.BudgetLineCreateInput, Prisma.BudgetLineUncheckedCreateInput>
  /**
   * In case the BudgetLine was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BudgetLineUpdateInput, Prisma.BudgetLineUncheckedUpdateInput>
}

/**
 * BudgetLine delete
 */
export type BudgetLineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
  /**
   * Filter which BudgetLine to delete.
   */
  where: Prisma.BudgetLineWhereUniqueInput
}

/**
 * BudgetLine deleteMany
 */
export type BudgetLineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BudgetLines to delete
   */
  where?: Prisma.BudgetLineWhereInput
  /**
   * Limit how many BudgetLines to delete.
   */
  limit?: number
}

/**
 * BudgetLine.approvedByUser
 */
export type BudgetLine$approvedByUserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * BudgetLine.expenses
 */
export type BudgetLine$expensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  where?: Prisma.ExpenseWhereInput
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  cursor?: Prisma.ExpenseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExpenseScalarFieldEnum | Prisma.ExpenseScalarFieldEnum[]
}

/**
 * BudgetLine without action
 */
export type BudgetLineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BudgetLine
   */
  select?: Prisma.BudgetLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BudgetLine
   */
  omit?: Prisma.BudgetLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetLineInclude<ExtArgs> | null
}
