
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Stakeholder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Stakeholder
 * 
 */
export type StakeholderModel = runtime.Types.Result.DefaultSelection<Prisma.$StakeholderPayload>

export type AggregateStakeholder = {
  _count: StakeholderCountAggregateOutputType | null
  _min: StakeholderMinAggregateOutputType | null
  _max: StakeholderMaxAggregateOutputType | null
}

export type StakeholderMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  userId: string | null
  power: $Enums.StakeholderPower | null
  interest: $Enums.StakeholderInterest | null
  influenceStrategy: string | null
}

export type StakeholderMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  userId: string | null
  power: $Enums.StakeholderPower | null
  interest: $Enums.StakeholderInterest | null
  influenceStrategy: string | null
}

export type StakeholderCountAggregateOutputType = {
  id: number
  projectId: number
  userId: number
  power: number
  interest: number
  influenceStrategy: number
  _all: number
}


export type StakeholderMinAggregateInputType = {
  id?: true
  projectId?: true
  userId?: true
  power?: true
  interest?: true
  influenceStrategy?: true
}

export type StakeholderMaxAggregateInputType = {
  id?: true
  projectId?: true
  userId?: true
  power?: true
  interest?: true
  influenceStrategy?: true
}

export type StakeholderCountAggregateInputType = {
  id?: true
  projectId?: true
  userId?: true
  power?: true
  interest?: true
  influenceStrategy?: true
  _all?: true
}

export type StakeholderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Stakeholder to aggregate.
   */
  where?: Prisma.StakeholderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stakeholders to fetch.
   */
  orderBy?: Prisma.StakeholderOrderByWithRelationInput | Prisma.StakeholderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StakeholderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stakeholders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stakeholders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Stakeholders
  **/
  _count?: true | StakeholderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StakeholderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StakeholderMaxAggregateInputType
}

export type GetStakeholderAggregateType<T extends StakeholderAggregateArgs> = {
      [P in keyof T & keyof AggregateStakeholder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStakeholder[P]>
    : Prisma.GetScalarType<T[P], AggregateStakeholder[P]>
}




export type StakeholderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StakeholderWhereInput
  orderBy?: Prisma.StakeholderOrderByWithAggregationInput | Prisma.StakeholderOrderByWithAggregationInput[]
  by: Prisma.StakeholderScalarFieldEnum[] | Prisma.StakeholderScalarFieldEnum
  having?: Prisma.StakeholderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StakeholderCountAggregateInputType | true
  _min?: StakeholderMinAggregateInputType
  _max?: StakeholderMaxAggregateInputType
}

export type StakeholderGroupByOutputType = {
  id: string
  projectId: string
  userId: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
  _count: StakeholderCountAggregateOutputType | null
  _min: StakeholderMinAggregateOutputType | null
  _max: StakeholderMaxAggregateOutputType | null
}

export type GetStakeholderGroupByPayload<T extends StakeholderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StakeholderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StakeholderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StakeholderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StakeholderGroupByOutputType[P]>
      }
    >
  >



export type StakeholderWhereInput = {
  AND?: Prisma.StakeholderWhereInput | Prisma.StakeholderWhereInput[]
  OR?: Prisma.StakeholderWhereInput[]
  NOT?: Prisma.StakeholderWhereInput | Prisma.StakeholderWhereInput[]
  id?: Prisma.StringFilter<"Stakeholder"> | string
  projectId?: Prisma.StringFilter<"Stakeholder"> | string
  userId?: Prisma.StringFilter<"Stakeholder"> | string
  power?: Prisma.EnumStakeholderPowerFilter<"Stakeholder"> | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFilter<"Stakeholder"> | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFilter<"Stakeholder"> | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type StakeholderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  power?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  influenceStrategy?: Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type StakeholderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StakeholderWhereInput | Prisma.StakeholderWhereInput[]
  OR?: Prisma.StakeholderWhereInput[]
  NOT?: Prisma.StakeholderWhereInput | Prisma.StakeholderWhereInput[]
  projectId?: Prisma.StringFilter<"Stakeholder"> | string
  userId?: Prisma.StringFilter<"Stakeholder"> | string
  power?: Prisma.EnumStakeholderPowerFilter<"Stakeholder"> | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFilter<"Stakeholder"> | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFilter<"Stakeholder"> | string
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type StakeholderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  power?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  influenceStrategy?: Prisma.SortOrder
  _count?: Prisma.StakeholderCountOrderByAggregateInput
  _max?: Prisma.StakeholderMaxOrderByAggregateInput
  _min?: Prisma.StakeholderMinOrderByAggregateInput
}

export type StakeholderScalarWhereWithAggregatesInput = {
  AND?: Prisma.StakeholderScalarWhereWithAggregatesInput | Prisma.StakeholderScalarWhereWithAggregatesInput[]
  OR?: Prisma.StakeholderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StakeholderScalarWhereWithAggregatesInput | Prisma.StakeholderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Stakeholder"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Stakeholder"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Stakeholder"> | string
  power?: Prisma.EnumStakeholderPowerWithAggregatesFilter<"Stakeholder"> | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestWithAggregatesFilter<"Stakeholder"> | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringWithAggregatesFilter<"Stakeholder"> | string
}

export type StakeholderCreateInput = {
  id: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
  project: Prisma.ProjectCreateNestedOneWithoutStakeholdersInput
  user: Prisma.UserCreateNestedOneWithoutStakeholdersInput
}

export type StakeholderUncheckedCreateInput = {
  id: string
  projectId: string
  userId: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
}

export type StakeholderUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutStakeholdersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutStakeholdersNestedInput
}

export type StakeholderUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StakeholderCreateManyInput = {
  id: string
  projectId: string
  userId: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
}

export type StakeholderUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StakeholderUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StakeholderListRelationFilter = {
  every?: Prisma.StakeholderWhereInput
  some?: Prisma.StakeholderWhereInput
  none?: Prisma.StakeholderWhereInput
}

export type StakeholderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StakeholderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  power?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  influenceStrategy?: Prisma.SortOrder
}

export type StakeholderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  power?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  influenceStrategy?: Prisma.SortOrder
}

export type StakeholderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  power?: Prisma.SortOrder
  interest?: Prisma.SortOrder
  influenceStrategy?: Prisma.SortOrder
}

export type StakeholderCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutUserInput, Prisma.StakeholderUncheckedCreateWithoutUserInput> | Prisma.StakeholderCreateWithoutUserInput[] | Prisma.StakeholderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutUserInput | Prisma.StakeholderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StakeholderCreateManyUserInputEnvelope
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
}

export type StakeholderUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutUserInput, Prisma.StakeholderUncheckedCreateWithoutUserInput> | Prisma.StakeholderCreateWithoutUserInput[] | Prisma.StakeholderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutUserInput | Prisma.StakeholderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StakeholderCreateManyUserInputEnvelope
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
}

export type StakeholderUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutUserInput, Prisma.StakeholderUncheckedCreateWithoutUserInput> | Prisma.StakeholderCreateWithoutUserInput[] | Prisma.StakeholderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutUserInput | Prisma.StakeholderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StakeholderUpsertWithWhereUniqueWithoutUserInput | Prisma.StakeholderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StakeholderCreateManyUserInputEnvelope
  set?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  disconnect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  delete?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  update?: Prisma.StakeholderUpdateWithWhereUniqueWithoutUserInput | Prisma.StakeholderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StakeholderUpdateManyWithWhereWithoutUserInput | Prisma.StakeholderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StakeholderScalarWhereInput | Prisma.StakeholderScalarWhereInput[]
}

export type StakeholderUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutUserInput, Prisma.StakeholderUncheckedCreateWithoutUserInput> | Prisma.StakeholderCreateWithoutUserInput[] | Prisma.StakeholderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutUserInput | Prisma.StakeholderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StakeholderUpsertWithWhereUniqueWithoutUserInput | Prisma.StakeholderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StakeholderCreateManyUserInputEnvelope
  set?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  disconnect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  delete?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  update?: Prisma.StakeholderUpdateWithWhereUniqueWithoutUserInput | Prisma.StakeholderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StakeholderUpdateManyWithWhereWithoutUserInput | Prisma.StakeholderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StakeholderScalarWhereInput | Prisma.StakeholderScalarWhereInput[]
}

export type StakeholderCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutProjectInput, Prisma.StakeholderUncheckedCreateWithoutProjectInput> | Prisma.StakeholderCreateWithoutProjectInput[] | Prisma.StakeholderUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutProjectInput | Prisma.StakeholderCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.StakeholderCreateManyProjectInputEnvelope
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
}

export type StakeholderUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutProjectInput, Prisma.StakeholderUncheckedCreateWithoutProjectInput> | Prisma.StakeholderCreateWithoutProjectInput[] | Prisma.StakeholderUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutProjectInput | Prisma.StakeholderCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.StakeholderCreateManyProjectInputEnvelope
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
}

export type StakeholderUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutProjectInput, Prisma.StakeholderUncheckedCreateWithoutProjectInput> | Prisma.StakeholderCreateWithoutProjectInput[] | Prisma.StakeholderUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutProjectInput | Prisma.StakeholderCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.StakeholderUpsertWithWhereUniqueWithoutProjectInput | Prisma.StakeholderUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.StakeholderCreateManyProjectInputEnvelope
  set?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  disconnect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  delete?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  update?: Prisma.StakeholderUpdateWithWhereUniqueWithoutProjectInput | Prisma.StakeholderUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.StakeholderUpdateManyWithWhereWithoutProjectInput | Prisma.StakeholderUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.StakeholderScalarWhereInput | Prisma.StakeholderScalarWhereInput[]
}

export type StakeholderUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.StakeholderCreateWithoutProjectInput, Prisma.StakeholderUncheckedCreateWithoutProjectInput> | Prisma.StakeholderCreateWithoutProjectInput[] | Prisma.StakeholderUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.StakeholderCreateOrConnectWithoutProjectInput | Prisma.StakeholderCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.StakeholderUpsertWithWhereUniqueWithoutProjectInput | Prisma.StakeholderUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.StakeholderCreateManyProjectInputEnvelope
  set?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  disconnect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  delete?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  connect?: Prisma.StakeholderWhereUniqueInput | Prisma.StakeholderWhereUniqueInput[]
  update?: Prisma.StakeholderUpdateWithWhereUniqueWithoutProjectInput | Prisma.StakeholderUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.StakeholderUpdateManyWithWhereWithoutProjectInput | Prisma.StakeholderUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.StakeholderScalarWhereInput | Prisma.StakeholderScalarWhereInput[]
}

export type EnumStakeholderPowerFieldUpdateOperationsInput = {
  set?: $Enums.StakeholderPower
}

export type EnumStakeholderInterestFieldUpdateOperationsInput = {
  set?: $Enums.StakeholderInterest
}

export type StakeholderCreateWithoutUserInput = {
  id: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
  project: Prisma.ProjectCreateNestedOneWithoutStakeholdersInput
}

export type StakeholderUncheckedCreateWithoutUserInput = {
  id: string
  projectId: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
}

export type StakeholderCreateOrConnectWithoutUserInput = {
  where: Prisma.StakeholderWhereUniqueInput
  create: Prisma.XOR<Prisma.StakeholderCreateWithoutUserInput, Prisma.StakeholderUncheckedCreateWithoutUserInput>
}

export type StakeholderCreateManyUserInputEnvelope = {
  data: Prisma.StakeholderCreateManyUserInput | Prisma.StakeholderCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type StakeholderUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.StakeholderWhereUniqueInput
  update: Prisma.XOR<Prisma.StakeholderUpdateWithoutUserInput, Prisma.StakeholderUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StakeholderCreateWithoutUserInput, Prisma.StakeholderUncheckedCreateWithoutUserInput>
}

export type StakeholderUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.StakeholderWhereUniqueInput
  data: Prisma.XOR<Prisma.StakeholderUpdateWithoutUserInput, Prisma.StakeholderUncheckedUpdateWithoutUserInput>
}

export type StakeholderUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.StakeholderScalarWhereInput
  data: Prisma.XOR<Prisma.StakeholderUpdateManyMutationInput, Prisma.StakeholderUncheckedUpdateManyWithoutUserInput>
}

export type StakeholderScalarWhereInput = {
  AND?: Prisma.StakeholderScalarWhereInput | Prisma.StakeholderScalarWhereInput[]
  OR?: Prisma.StakeholderScalarWhereInput[]
  NOT?: Prisma.StakeholderScalarWhereInput | Prisma.StakeholderScalarWhereInput[]
  id?: Prisma.StringFilter<"Stakeholder"> | string
  projectId?: Prisma.StringFilter<"Stakeholder"> | string
  userId?: Prisma.StringFilter<"Stakeholder"> | string
  power?: Prisma.EnumStakeholderPowerFilter<"Stakeholder"> | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFilter<"Stakeholder"> | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFilter<"Stakeholder"> | string
}

export type StakeholderCreateWithoutProjectInput = {
  id: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
  user: Prisma.UserCreateNestedOneWithoutStakeholdersInput
}

export type StakeholderUncheckedCreateWithoutProjectInput = {
  id: string
  userId: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
}

export type StakeholderCreateOrConnectWithoutProjectInput = {
  where: Prisma.StakeholderWhereUniqueInput
  create: Prisma.XOR<Prisma.StakeholderCreateWithoutProjectInput, Prisma.StakeholderUncheckedCreateWithoutProjectInput>
}

export type StakeholderCreateManyProjectInputEnvelope = {
  data: Prisma.StakeholderCreateManyProjectInput | Prisma.StakeholderCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type StakeholderUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.StakeholderWhereUniqueInput
  update: Prisma.XOR<Prisma.StakeholderUpdateWithoutProjectInput, Prisma.StakeholderUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.StakeholderCreateWithoutProjectInput, Prisma.StakeholderUncheckedCreateWithoutProjectInput>
}

export type StakeholderUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.StakeholderWhereUniqueInput
  data: Prisma.XOR<Prisma.StakeholderUpdateWithoutProjectInput, Prisma.StakeholderUncheckedUpdateWithoutProjectInput>
}

export type StakeholderUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.StakeholderScalarWhereInput
  data: Prisma.XOR<Prisma.StakeholderUpdateManyMutationInput, Prisma.StakeholderUncheckedUpdateManyWithoutProjectInput>
}

export type StakeholderCreateManyUserInput = {
  id: string
  projectId: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
}

export type StakeholderUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutStakeholdersNestedInput
}

export type StakeholderUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StakeholderUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StakeholderCreateManyProjectInput = {
  id: string
  userId: string
  power: $Enums.StakeholderPower
  interest: $Enums.StakeholderInterest
  influenceStrategy: string
}

export type StakeholderUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutStakeholdersNestedInput
}

export type StakeholderUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StakeholderUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  power?: Prisma.EnumStakeholderPowerFieldUpdateOperationsInput | $Enums.StakeholderPower
  interest?: Prisma.EnumStakeholderInterestFieldUpdateOperationsInput | $Enums.StakeholderInterest
  influenceStrategy?: Prisma.StringFieldUpdateOperationsInput | string
}



export type StakeholderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  userId?: boolean
  power?: boolean
  interest?: boolean
  influenceStrategy?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stakeholder"]>

export type StakeholderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  userId?: boolean
  power?: boolean
  interest?: boolean
  influenceStrategy?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stakeholder"]>

export type StakeholderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  userId?: boolean
  power?: boolean
  interest?: boolean
  influenceStrategy?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stakeholder"]>

export type StakeholderSelectScalar = {
  id?: boolean
  projectId?: boolean
  userId?: boolean
  power?: boolean
  interest?: boolean
  influenceStrategy?: boolean
}

export type StakeholderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "userId" | "power" | "interest" | "influenceStrategy", ExtArgs["result"]["stakeholder"]>
export type StakeholderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type StakeholderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type StakeholderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $StakeholderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Stakeholder"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    userId: string
    power: $Enums.StakeholderPower
    interest: $Enums.StakeholderInterest
    influenceStrategy: string
  }, ExtArgs["result"]["stakeholder"]>
  composites: {}
}

export type StakeholderGetPayload<S extends boolean | null | undefined | StakeholderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StakeholderPayload, S>

export type StakeholderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StakeholderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StakeholderCountAggregateInputType | true
  }

export interface StakeholderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Stakeholder'], meta: { name: 'Stakeholder' } }
  /**
   * Find zero or one Stakeholder that matches the filter.
   * @param {StakeholderFindUniqueArgs} args - Arguments to find a Stakeholder
   * @example
   * // Get one Stakeholder
   * const stakeholder = await prisma.stakeholder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StakeholderFindUniqueArgs>(args: Prisma.SelectSubset<T, StakeholderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Stakeholder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StakeholderFindUniqueOrThrowArgs} args - Arguments to find a Stakeholder
   * @example
   * // Get one Stakeholder
   * const stakeholder = await prisma.stakeholder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StakeholderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StakeholderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Stakeholder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakeholderFindFirstArgs} args - Arguments to find a Stakeholder
   * @example
   * // Get one Stakeholder
   * const stakeholder = await prisma.stakeholder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StakeholderFindFirstArgs>(args?: Prisma.SelectSubset<T, StakeholderFindFirstArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Stakeholder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakeholderFindFirstOrThrowArgs} args - Arguments to find a Stakeholder
   * @example
   * // Get one Stakeholder
   * const stakeholder = await prisma.stakeholder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StakeholderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StakeholderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Stakeholders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakeholderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Stakeholders
   * const stakeholders = await prisma.stakeholder.findMany()
   * 
   * // Get first 10 Stakeholders
   * const stakeholders = await prisma.stakeholder.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stakeholderWithIdOnly = await prisma.stakeholder.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StakeholderFindManyArgs>(args?: Prisma.SelectSubset<T, StakeholderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Stakeholder.
   * @param {StakeholderCreateArgs} args - Arguments to create a Stakeholder.
   * @example
   * // Create one Stakeholder
   * const Stakeholder = await prisma.stakeholder.create({
   *   data: {
   *     // ... data to create a Stakeholder
   *   }
   * })
   * 
   */
  create<T extends StakeholderCreateArgs>(args: Prisma.SelectSubset<T, StakeholderCreateArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Stakeholders.
   * @param {StakeholderCreateManyArgs} args - Arguments to create many Stakeholders.
   * @example
   * // Create many Stakeholders
   * const stakeholder = await prisma.stakeholder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StakeholderCreateManyArgs>(args?: Prisma.SelectSubset<T, StakeholderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Stakeholders and returns the data saved in the database.
   * @param {StakeholderCreateManyAndReturnArgs} args - Arguments to create many Stakeholders.
   * @example
   * // Create many Stakeholders
   * const stakeholder = await prisma.stakeholder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Stakeholders and only return the `id`
   * const stakeholderWithIdOnly = await prisma.stakeholder.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StakeholderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StakeholderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Stakeholder.
   * @param {StakeholderDeleteArgs} args - Arguments to delete one Stakeholder.
   * @example
   * // Delete one Stakeholder
   * const Stakeholder = await prisma.stakeholder.delete({
   *   where: {
   *     // ... filter to delete one Stakeholder
   *   }
   * })
   * 
   */
  delete<T extends StakeholderDeleteArgs>(args: Prisma.SelectSubset<T, StakeholderDeleteArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Stakeholder.
   * @param {StakeholderUpdateArgs} args - Arguments to update one Stakeholder.
   * @example
   * // Update one Stakeholder
   * const stakeholder = await prisma.stakeholder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StakeholderUpdateArgs>(args: Prisma.SelectSubset<T, StakeholderUpdateArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Stakeholders.
   * @param {StakeholderDeleteManyArgs} args - Arguments to filter Stakeholders to delete.
   * @example
   * // Delete a few Stakeholders
   * const { count } = await prisma.stakeholder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StakeholderDeleteManyArgs>(args?: Prisma.SelectSubset<T, StakeholderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stakeholders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakeholderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Stakeholders
   * const stakeholder = await prisma.stakeholder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StakeholderUpdateManyArgs>(args: Prisma.SelectSubset<T, StakeholderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stakeholders and returns the data updated in the database.
   * @param {StakeholderUpdateManyAndReturnArgs} args - Arguments to update many Stakeholders.
   * @example
   * // Update many Stakeholders
   * const stakeholder = await prisma.stakeholder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Stakeholders and only return the `id`
   * const stakeholderWithIdOnly = await prisma.stakeholder.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StakeholderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StakeholderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Stakeholder.
   * @param {StakeholderUpsertArgs} args - Arguments to update or create a Stakeholder.
   * @example
   * // Update or create a Stakeholder
   * const stakeholder = await prisma.stakeholder.upsert({
   *   create: {
   *     // ... data to create a Stakeholder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Stakeholder we want to update
   *   }
   * })
   */
  upsert<T extends StakeholderUpsertArgs>(args: Prisma.SelectSubset<T, StakeholderUpsertArgs<ExtArgs>>): Prisma.Prisma__StakeholderClient<runtime.Types.Result.GetResult<Prisma.$StakeholderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Stakeholders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakeholderCountArgs} args - Arguments to filter Stakeholders to count.
   * @example
   * // Count the number of Stakeholders
   * const count = await prisma.stakeholder.count({
   *   where: {
   *     // ... the filter for the Stakeholders we want to count
   *   }
   * })
  **/
  count<T extends StakeholderCountArgs>(
    args?: Prisma.Subset<T, StakeholderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StakeholderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Stakeholder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakeholderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StakeholderAggregateArgs>(args: Prisma.Subset<T, StakeholderAggregateArgs>): Prisma.PrismaPromise<GetStakeholderAggregateType<T>>

  /**
   * Group by Stakeholder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StakeholderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StakeholderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StakeholderGroupByArgs['orderBy'] }
      : { orderBy?: StakeholderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StakeholderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStakeholderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Stakeholder model
 */
readonly fields: StakeholderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Stakeholder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StakeholderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Stakeholder model
 */
export interface StakeholderFieldRefs {
  readonly id: Prisma.FieldRef<"Stakeholder", 'String'>
  readonly projectId: Prisma.FieldRef<"Stakeholder", 'String'>
  readonly userId: Prisma.FieldRef<"Stakeholder", 'String'>
  readonly power: Prisma.FieldRef<"Stakeholder", 'StakeholderPower'>
  readonly interest: Prisma.FieldRef<"Stakeholder", 'StakeholderInterest'>
  readonly influenceStrategy: Prisma.FieldRef<"Stakeholder", 'String'>
}
    

// Custom InputTypes
/**
 * Stakeholder findUnique
 */
export type StakeholderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * Filter, which Stakeholder to fetch.
   */
  where: Prisma.StakeholderWhereUniqueInput
}

/**
 * Stakeholder findUniqueOrThrow
 */
export type StakeholderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * Filter, which Stakeholder to fetch.
   */
  where: Prisma.StakeholderWhereUniqueInput
}

/**
 * Stakeholder findFirst
 */
export type StakeholderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * Filter, which Stakeholder to fetch.
   */
  where?: Prisma.StakeholderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stakeholders to fetch.
   */
  orderBy?: Prisma.StakeholderOrderByWithRelationInput | Prisma.StakeholderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stakeholders.
   */
  cursor?: Prisma.StakeholderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stakeholders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stakeholders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stakeholders.
   */
  distinct?: Prisma.StakeholderScalarFieldEnum | Prisma.StakeholderScalarFieldEnum[]
}

/**
 * Stakeholder findFirstOrThrow
 */
export type StakeholderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * Filter, which Stakeholder to fetch.
   */
  where?: Prisma.StakeholderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stakeholders to fetch.
   */
  orderBy?: Prisma.StakeholderOrderByWithRelationInput | Prisma.StakeholderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Stakeholders.
   */
  cursor?: Prisma.StakeholderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stakeholders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stakeholders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stakeholders.
   */
  distinct?: Prisma.StakeholderScalarFieldEnum | Prisma.StakeholderScalarFieldEnum[]
}

/**
 * Stakeholder findMany
 */
export type StakeholderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * Filter, which Stakeholders to fetch.
   */
  where?: Prisma.StakeholderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Stakeholders to fetch.
   */
  orderBy?: Prisma.StakeholderOrderByWithRelationInput | Prisma.StakeholderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Stakeholders.
   */
  cursor?: Prisma.StakeholderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Stakeholders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Stakeholders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Stakeholders.
   */
  distinct?: Prisma.StakeholderScalarFieldEnum | Prisma.StakeholderScalarFieldEnum[]
}

/**
 * Stakeholder create
 */
export type StakeholderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * The data needed to create a Stakeholder.
   */
  data: Prisma.XOR<Prisma.StakeholderCreateInput, Prisma.StakeholderUncheckedCreateInput>
}

/**
 * Stakeholder createMany
 */
export type StakeholderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Stakeholders.
   */
  data: Prisma.StakeholderCreateManyInput | Prisma.StakeholderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Stakeholder createManyAndReturn
 */
export type StakeholderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * The data used to create many Stakeholders.
   */
  data: Prisma.StakeholderCreateManyInput | Prisma.StakeholderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Stakeholder update
 */
export type StakeholderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * The data needed to update a Stakeholder.
   */
  data: Prisma.XOR<Prisma.StakeholderUpdateInput, Prisma.StakeholderUncheckedUpdateInput>
  /**
   * Choose, which Stakeholder to update.
   */
  where: Prisma.StakeholderWhereUniqueInput
}

/**
 * Stakeholder updateMany
 */
export type StakeholderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Stakeholders.
   */
  data: Prisma.XOR<Prisma.StakeholderUpdateManyMutationInput, Prisma.StakeholderUncheckedUpdateManyInput>
  /**
   * Filter which Stakeholders to update
   */
  where?: Prisma.StakeholderWhereInput
  /**
   * Limit how many Stakeholders to update.
   */
  limit?: number
}

/**
 * Stakeholder updateManyAndReturn
 */
export type StakeholderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * The data used to update Stakeholders.
   */
  data: Prisma.XOR<Prisma.StakeholderUpdateManyMutationInput, Prisma.StakeholderUncheckedUpdateManyInput>
  /**
   * Filter which Stakeholders to update
   */
  where?: Prisma.StakeholderWhereInput
  /**
   * Limit how many Stakeholders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Stakeholder upsert
 */
export type StakeholderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * The filter to search for the Stakeholder to update in case it exists.
   */
  where: Prisma.StakeholderWhereUniqueInput
  /**
   * In case the Stakeholder found by the `where` argument doesn't exist, create a new Stakeholder with this data.
   */
  create: Prisma.XOR<Prisma.StakeholderCreateInput, Prisma.StakeholderUncheckedCreateInput>
  /**
   * In case the Stakeholder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StakeholderUpdateInput, Prisma.StakeholderUncheckedUpdateInput>
}

/**
 * Stakeholder delete
 */
export type StakeholderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
  /**
   * Filter which Stakeholder to delete.
   */
  where: Prisma.StakeholderWhereUniqueInput
}

/**
 * Stakeholder deleteMany
 */
export type StakeholderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Stakeholders to delete
   */
  where?: Prisma.StakeholderWhereInput
  /**
   * Limit how many Stakeholders to delete.
   */
  limit?: number
}

/**
 * Stakeholder without action
 */
export type StakeholderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Stakeholder
   */
  select?: Prisma.StakeholderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stakeholder
   */
  omit?: Prisma.StakeholderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StakeholderInclude<ExtArgs> | null
}
